### ISSUE TITLE
Get Google Cloud Platform ready for deploy gateway server

### ISSUE THREAD

**Issue by arichen** [codeforsanjose/open311-ionic#9]
Prepare the cloud server for 311 gateway server

**Comment by clarle** [comment]
@arichen @3vivekb I don't have as much experience with GCP, but I'm pretty knowledgeable with AWS.

Is there some particular reason we want to use GCP instead of AWS?  I'm happy to give it a shot, but just want to make sure there's a good business reason for us to do so.  

If @3vivekb is more familiar with GCP, then I'm all for it.

**Comment by 3vivekb** [comment]
Hey @clarle Yea i'm more familiar with GCP.  Also I think it's more user-friendly.  Unfortunately I just found out Code for America is not getting free GCP bux anymore so I might need to switch to AWS.  And find our AWS credits.

**Comment by clarle** [comment]
I'm going to close this issue out, so we can focus more on frontend issues in this repository.

Deployment and backend issues should be filed on [codeforsanjose/open311_gateway](https://github.com/codeforsanjose/open311_gateway).
